// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {llm} from '../models';
import {db} from '../models';

export function AISearch(arg1:string):Promise<Array<llm.AISearchResult>>;

export function DownloadLLM():Promise<string>;

export function GetSettings():Promise<Record<string, any>>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function ScanDirectory(arg1:string):Promise<void>;

export function Search(arg1:string):Promise<Array<db.SearchResult>>;
