// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AISearch(arg1) {
  return window['go']['main']['App']['AISearch'](arg1);
}

export function ClearDatabase() {
  return window['go']['main']['App']['ClearDatabase']();
}

export function DownloadLLM() {
  return window['go']['main']['App']['DownloadLLM']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function ScanDirectory(arg1) {
  return window['go']['main']['App']['ScanDirectory'](arg1);
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}
